/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it.gsm.trackingsystem.testmachine;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author abdhul
 */
public class LoginFrame extends javax.swing.JFrame {
    private TestMachineForm parentForm;
    TestMachine testMachine;

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame(TestMachineForm parentForm, TestMachine testMachine) {
        // Sets icon
        ImageIcon icon = new ImageIcon(getClass().getResource("/it/gsm/trackingsystem/testmachine/favicon.png"));
        setIconImage(icon.getImage());
        this.parentForm = parentForm;
        this.testMachine = testMachine;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newUserFrame = new javax.swing.JFrame();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        newNameTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        newSurnameTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        newUsernameTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        sendNewUserToDatabaseButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        newUserPasswordField = new javax.swing.JPasswordField();
        newUserRepeatPasswordField = new javax.swing.JPasswordField();
        changePasswordFrame = new javax.swing.JFrame();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        usernameChangePasswordFrameTextField = new javax.swing.JTextField();
        oldPasswordUsernameChangePasswordFrameTextField = new javax.swing.JPasswordField();
        newPasswordChangePasswordFrameTextField = new javax.swing.JPasswordField();
        repeatedPasswordChangePasswordFrameTextField = new javax.swing.JPasswordField();
        changePasswordButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        newUserMenuItem = new javax.swing.JMenuItem();
        changePasswordMenuItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        settingsMenuItem = new javax.swing.JMenuItem();

        newUserFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        newUserFrame.setTitle("Tracking System - Nuovo utente");
        newUserFrame.setResizable(false);
        newUserFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                newUserFrameWindowClosing(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Inserisci i tuoi dati:");

        jLabel7.setText("Nome:");

        jLabel8.setText("Cognome:");

        jLabel9.setText("Username:");

        jLabel10.setText("Password:");

        sendNewUserToDatabaseButton.setText("Ok");
        sendNewUserToDatabaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendNewUserToDatabaseButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Ripeti password:");

        javax.swing.GroupLayout newUserFrameLayout = new javax.swing.GroupLayout(newUserFrame.getContentPane());
        newUserFrame.getContentPane().setLayout(newUserFrameLayout);
        newUserFrameLayout.setHorizontalGroup(
            newUserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newUserFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newUserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newUserFrameLayout.createSequentialGroup()
                        .addGroup(newUserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(newUserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(newSurnameTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(newUsernameTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(newNameTextField)
                            .addComponent(newUserPasswordField)
                            .addComponent(newUserRepeatPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newUserFrameLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(sendNewUserToDatabaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        newUserFrameLayout.setVerticalGroup(
            newUserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newUserFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(newUserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(newNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newUserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(newSurnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newUserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(newUsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newUserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(newUserPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newUserFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(newUserRepeatPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(sendNewUserToDatabaseButton)
                .addContainerGap())
        );

        changePasswordFrame.setPreferredSize(new java.awt.Dimension(342, 249));
        changePasswordFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                changePasswordFrameWindowClosing(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Inserici i tuoi dati:");

        jLabel11.setText("Username:");

        jLabel12.setText("Vecchia password:");

        jLabel13.setText("Nuova password:");

        jLabel14.setText("Ripeti nuova password:");

        changePasswordButton.setText("Cambia password");
        changePasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout changePasswordFrameLayout = new javax.swing.GroupLayout(changePasswordFrame.getContentPane());
        changePasswordFrame.getContentPane().setLayout(changePasswordFrameLayout);
        changePasswordFrameLayout.setHorizontalGroup(
            changePasswordFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePasswordFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(changePasswordFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(changePasswordFrameLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(usernameChangePasswordFrameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(changePasswordFrameLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(oldPasswordUsernameChangePasswordFrameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, changePasswordFrameLayout.createSequentialGroup()
                        .addGroup(changePasswordFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(changePasswordFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(repeatedPasswordChangePasswordFrameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(newPasswordChangePasswordFrameTextField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, changePasswordFrameLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(changePasswordButton)))
                .addContainerGap())
        );
        changePasswordFrameLayout.setVerticalGroup(
            changePasswordFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePasswordFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(changePasswordFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(usernameChangePasswordFrameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(changePasswordFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(oldPasswordUsernameChangePasswordFrameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(changePasswordFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(newPasswordChangePasswordFrameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(changePasswordFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(repeatedPasswordChangePasswordFrameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(changePasswordButton)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tracking System - Login");
        setResizable(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tracking system login");

        jLabel2.setText("Username");

        jLabel3.setText("Password");

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        jMenu2.setText("Operatore");

        newUserMenuItem.setText("Nuovo utente");
        newUserMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newUserMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(newUserMenuItem);

        changePasswordMenuItem.setText("Cambio password");
        changePasswordMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(changePasswordMenuItem);

        jMenuItem1.setText("Cambio password (aiuto da amministratore)");
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Impostazioni");

        settingsMenuItem.setText("Impostazioni");
        settingsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(settingsMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(usernameTextField))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(loginButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        //parentForm.setVisible(true);
        login();
    }//GEN-LAST:event_loginButtonActionPerformed

    private void sendNewUserToDatabaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendNewUserToDatabaseButtonActionPerformed
        // TODO add your handling code here:
        String password = new String(newUserPasswordField.getPassword());
        String repeatedPassword = new String(newUserRepeatPasswordField.getPassword());
        if(newNameTextField.getText().equals("")
                || newSurnameTextField.getText().equals("")
                || newUsernameTextField.getText().equals("")
                || password.equals("")){
            String error = "Non possono esserci campi nulli!";
            JOptionPane.showMessageDialog(newUserFrame, error, "Errore", JOptionPane.ERROR_MESSAGE);
        }
        else if(!password.equals(repeatedPassword)){
            String error = "Le pasword non corrispondono!";
            JOptionPane.showMessageDialog(newUserFrame, error, "Attenzione", JOptionPane.WARNING_MESSAGE);
        }
        else if(testMachine.newUser(newNameTextField.getText(),
                    newSurnameTextField.getText(),
                    newUsernameTextField.getText(),
                    password)){
                usernameTextField.setText(newUsernameTextField.getText());
                passwordField.setText(password);
                newUserFrame.dispose();
                this.setEnabled(true);
        }
    }//GEN-LAST:event_sendNewUserToDatabaseButtonActionPerformed

    private void newUserFrameWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_newUserFrameWindowClosing
        // TODO add your handling code here:
        this.setEnabled(true);
        newNameTextField.setText("");
        newSurnameTextField.setText("");
        newUsernameTextField.setText("");
        newUserPasswordField.setText("");
        newUserRepeatPasswordField.setText("");
    }//GEN-LAST:event_newUserFrameWindowClosing

    private void settingsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsMenuItemActionPerformed
        this.setEnabled(false);
        new settingsFrame(this, testMachine).setVisible(true);
    }//GEN-LAST:event_settingsMenuItemActionPerformed

    private void newUserMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newUserMenuItemActionPerformed
        // TODO add your handling code here:
        newUserFrame.pack();
        newUserFrame.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_newUserMenuItemActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
        login();
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void changePasswordMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordMenuItemActionPerformed
        // TODO add your handling code here:
        changePasswordFrame.pack();
        changePasswordFrame.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_changePasswordMenuItemActionPerformed

    private void changePasswordFrameWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_changePasswordFrameWindowClosing
        // TODO add your handling code here:
        usernameChangePasswordFrameTextField.setText("");
        oldPasswordUsernameChangePasswordFrameTextField.setText("");
        newPasswordChangePasswordFrameTextField.setText("");
        repeatedPasswordChangePasswordFrameTextField.setText("");
        this.setEnabled(true);
    }//GEN-LAST:event_changePasswordFrameWindowClosing

    private void changePasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordButtonActionPerformed
        String username = usernameChangePasswordFrameTextField.getText();
        String oldPassword = new String(oldPasswordUsernameChangePasswordFrameTextField.getPassword());
        String newPassword = new String(newPasswordChangePasswordFrameTextField.getPassword());
        String repeatedNewPassword = new String(repeatedPasswordChangePasswordFrameTextField.getPassword());
        if(!newPassword.equals(repeatedNewPassword)){
            String error = "Le pasword non corrispondono!";
            JOptionPane.showMessageDialog(changePasswordFrame, error, "Attenzione", JOptionPane.WARNING_MESSAGE);
        }
        // Attempts to change password
        else if(testMachine.changePassword(username, oldPassword, newPassword)){
            this.setEnabled(true);
            String message = "Password cambiata!";
            JOptionPane.showMessageDialog(changePasswordFrame, message, "Password cambiata", JOptionPane.PLAIN_MESSAGE);
            changePasswordFrame.dispose();
        }
    }//GEN-LAST:event_changePasswordButtonActionPerformed

    private void login(){
        String password = new String(passwordField.getPassword());
        if (testMachine.login(usernameTextField.getText(), password)){
            //parentForm.setVisible(true);
            this.dispose();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changePasswordButton;
    private javax.swing.JFrame changePasswordFrame;
    private javax.swing.JMenuItem changePasswordMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextField newNameTextField;
    private javax.swing.JPasswordField newPasswordChangePasswordFrameTextField;
    private javax.swing.JTextField newSurnameTextField;
    private javax.swing.JFrame newUserFrame;
    private javax.swing.JMenuItem newUserMenuItem;
    private javax.swing.JPasswordField newUserPasswordField;
    private javax.swing.JPasswordField newUserRepeatPasswordField;
    private javax.swing.JTextField newUsernameTextField;
    private javax.swing.JPasswordField oldPasswordUsernameChangePasswordFrameTextField;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JPasswordField repeatedPasswordChangePasswordFrameTextField;
    private javax.swing.JButton sendNewUserToDatabaseButton;
    private javax.swing.JMenuItem settingsMenuItem;
    private javax.swing.JTextField usernameChangePasswordFrameTextField;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
